import { execFileSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { runAnalysis } from "../src/core/service";

const sourceUrl = "https://github.com/sindresorhus/p-limit.git";
const commit = "df476048d023ff868cd45b35ee47f5fb0ca2b25a";
const destination = path.resolve("generated", "case-study", "p-limit");
const task = "Change limitFunction concurrency behavior";
const goldFiles = [
  { path: "index.js", rationale: "Runtime implementation and its pLimit dependency." },
  { path: "index.d.ts", rationale: "Public LimitFunction and Options contracts." },
  { path: "test.js", rationale: "Runtime behavior tests importing the package entry point." },
  { path: "index.test-d.ts", rationale: "Public type-contract tests importing the package entry point." },
];

function git(args: string[], cwd?: string): string {
  return execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
}

async function prepare(): Promise<void> {
  await mkdir(path.dirname(destination), { recursive: true });
  try {
    const existingCommit = git(["rev-parse", "HEAD"], destination);
    const existingOrigin = git(["remote", "get-url", "origin"], destination);
    if (existingCommit !== commit || existingOrigin !== sourceUrl) {
      throw new Error(`Existing case-study checkout must be ${sourceUrl} at ${commit}; found ${existingOrigin} at ${existingCommit}.`);
    }
  } catch (error) {
    if (error instanceof Error && error.message.startsWith("Existing case-study")) throw error;
    git(["init", destination]);
    git(["-C", destination, "remote", "add", "origin", sourceUrl]);
    git(["-C", destination, "fetch", "--depth", "1", "origin", commit]);
    git(["-C", destination, "checkout", "--detach", "FETCH_HEAD"]);
  }
}

await prepare();
const result = await runAnalysis({ repository: destination, task, budget: 4_000, depth: 3, writeArtifacts: false });
const limit = 10;
const graphFiles = [...new Set(result.impact.recommendations.map((item) => item.path))].slice(0, limit);
const lexicalFiles = [...new Set(result.baseline.map((item) => item.path).filter((file): file is string => typeof file === "string"))].slice(0, limit);
const gold = new Set(goldFiles.map((item) => item.path));
const graphHits = graphFiles.filter((file) => gold.has(file));
const lexicalHits = lexicalFiles.filter((file) => gold.has(file));
const evidence = result.impact.recommendations
  .filter((item) => gold.has(item.path))
  .map((item) => ({ path: item.path, symbol: item.symbol, score: item.score, risk: item.risk, evidencePath: item.evidenceText }));

if (git(["rev-parse", "HEAD"], destination) !== commit) throw new Error("Case-study commit changed during analysis.");
if (!result.impact.seeds.some((seed) => seed.node.properties.name === "limitFunction")) throw new Error("p-limit seed resolution failed.");
if (graphHits.length !== gold.size) throw new Error(`Graph retrieval found ${graphHits.length}/${gold.size} gold files.`);
if (!graphFiles.includes("test.js") || !graphFiles.includes("index.test-d.ts")) throw new Error("Structural test retrieval failed.");

const report = {
  schemaVersion: 1,
  generatedAt: new Date().toISOString(),
  command: "pnpm case-study",
  environment: { node: process.version, platform: `${process.platform}/${process.arch}` },
  source: { repository: sourceUrl, commit, license: "MIT", checkout: "generated/case-study/p-limit (ignored)" },
  task,
  resultLimit: limit,
  graph: {
    nodes: result.impact.graphCounts.nodes,
    edges: result.impact.graphCounts.edges,
    recommendations: result.impact.recommendations.length,
    files: graphFiles,
    hits: graphHits,
    recallAtK: graphHits.length / gold.size,
  },
  lexical: { files: lexicalFiles, hits: lexicalHits, recallAtK: lexicalHits.length / gold.size },
  goldFiles,
  evidence,
  context: { estimatedTokens: result.contextPack.estimatedTokens, budget: result.contextPack.analysis.budget },
  latencyMs: {
    indexing: result.index.diagnostics.elapsedMs,
    ingestion: Number(result.ingestion.batches.reduce((sum, batch) => sum + batch.latencyMs, 0).toFixed(2)),
    retrieval: Number(result.impact.queryReceipts.reduce((sum, receipt) => sum + receipt.latencyMs, 0).toFixed(2)),
  },
};

const markdown = `# External case study: p-limit

This report was generated by \`${report.command}\` against the real, unmodified [p-limit](${sourceUrl.replace(".git", "")}) repository at commit \`${commit}\`. The checkout is ignored and is not redistributed by HydraTrace.

## Scenario

- Task: **${task}**
- Source license: MIT
- Result limit: ${limit} files per retriever
- HydraDB graph: ${report.graph.nodes} nodes / ${report.graph.edges} edges
- Context Pack: ${report.context.estimatedTokens}/${report.context.budget} estimated tokens

| Retriever | Gold hits | Recall@${limit} | Returned files |
| --- | ---: | ---: | --- |
| HydraTrace graph | ${graphHits.length}/${gold.size} | ${(report.graph.recallAtK * 100).toFixed(1)}% | ${graphFiles.map((file) => `\`${file}\``).join(", ")} |
| Lexical baseline | ${lexicalHits.length}/${gold.size} | ${(report.lexical.recallAtK * 100).toFixed(1)}% | ${lexicalFiles.map((file) => `\`${file}\``).join(", ")} |

The lexical baseline resolves the named implementation and declaration. HydraDB traversal additionally reaches both runtime and type tests through import/definition structure. This is one pinned case study, not a general quality claim.

## Evidence

${evidence.map((item) => `- \`${item.path}${item.symbol ? `:${item.symbol}` : ""}\` — ${item.risk} ${item.score.toFixed(3)} — \`${item.evidencePath}\``).join("\n")}

## Gold rationale

${goldFiles.map((item) => `- \`${item.path}\`: ${item.rationale}`).join("\n")}

## Reproduction metadata

- Generated: ${report.generatedAt}
- Node: ${report.environment.node}
- Platform: ${report.environment.platform}
- Indexing: ${report.latencyMs.indexing.toFixed(2)} ms
- HydraDB ingestion mutations: ${report.latencyMs.ingestion.toFixed(2)} ms
- HydraDB retrieval queries: ${report.latencyMs.retrieval.toFixed(2)} ms

Latencies are a single local run and are not presented as a benchmark. Gold labels were authored for this scenario and are shown above so the comparison remains auditable.
`;

await writeFile(path.resolve("generated", "case-study", "p-limit-report.json"), `${JSON.stringify(report, null, 2)}\n`, "utf8");
await writeFile(path.resolve("docs", "CASE_STUDY.md"), markdown, "utf8");
console.log(`PASS  p-limit ${commit.slice(0, 12)} indexed: ${report.graph.nodes} nodes / ${report.graph.edges} edges`);
console.log(`PASS  Graph Recall@${limit} ${(report.graph.recallAtK * 100).toFixed(1)}% vs lexical ${(report.lexical.recallAtK * 100).toFixed(1)}% (${gold.size} gold files)`);
console.log(`PASS  Structural test hits: test.js, index.test-d.ts`);
console.log(`PASS  Wrote docs/CASE_STUDY.md and generated/case-study/p-limit-report.json`);
